package com.gyhqq.domain.cargo;

import java.io.Serializable;
import java.util.Date;

public class Finance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.FINANCE_ID
     *
     * @mbg.generated
     */
    private String financeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.INPUT_DATE
     *
     * @mbg.generated
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.INPUT_BY
     *
     * @mbg.generated
     */
    private String inputBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.STATE
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.CREATE_DEPT
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.FINANCE_ID
     *
     * @return the value of co_finance.FINANCE_ID
     * @mbg.generated
     */
    public String getFinanceId() {
        return financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.FINANCE_ID
     *
     * @param financeId the value for co_finance.FINANCE_ID
     * @mbg.generated
     */
    public void setFinanceId(String financeId) {
        this.financeId = financeId == null ? null : financeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.INPUT_DATE
     *
     * @return the value of co_finance.INPUT_DATE
     * @mbg.generated
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.INPUT_DATE
     *
     * @param inputDate the value for co_finance.INPUT_DATE
     * @mbg.generated
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.INPUT_BY
     *
     * @return the value of co_finance.INPUT_BY
     * @mbg.generated
     */
    public String getInputBy() {
        return inputBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.INPUT_BY
     *
     * @param inputBy the value for co_finance.INPUT_BY
     * @mbg.generated
     */
    public void setInputBy(String inputBy) {
        this.inputBy = inputBy == null ? null : inputBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.STATE
     *
     * @return the value of co_finance.STATE
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.STATE
     *
     * @param state the value for co_finance.STATE
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.CREATE_BY
     *
     * @return the value of co_finance.CREATE_BY
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.CREATE_BY
     *
     * @param createBy the value for co_finance.CREATE_BY
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.CREATE_DEPT
     *
     * @return the value of co_finance.CREATE_DEPT
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.CREATE_DEPT
     *
     * @param createDept the value for co_finance.CREATE_DEPT
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.CREATE_TIME
     *
     * @return the value of co_finance.CREATE_TIME
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.CREATE_TIME
     *
     * @param createTime the value for co_finance.CREATE_TIME
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}