package com.gyhqq.dao.system;

import com.gyhqq.domain.system.Chat;
import com.gyhqq.domain.system.ChatExample;

import java.util.List;

public interface ChatDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_chat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String chatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_chat
     *
     * @mbg.generated
     */
    int insert(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_chat
     *
     * @mbg.generated
     */
    int insertSelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_chat
     *
     * @mbg.generated
     */
    List<Chat> selectByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_chat
     *
     * @mbg.generated
     */
    Chat selectByPrimaryKey(String chatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_chat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_chat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Chat record);
}