package com.gyhqq.dao.cargo;

import com.gyhqq.domain.cargo.ExtEproduct;
import com.gyhqq.domain.cargo.ExtEproductExample;

import java.util.List;

public interface ExtEproductDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    void deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    void insert(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    void insertSelective(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    List<ExtEproduct> selectByExampleWithBLOBs(ExtEproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    List<ExtEproduct> selectByExample(ExtEproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    ExtEproduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    void updateByPrimaryKeySelective(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    void updateByPrimaryKeyWithBLOBs(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    void updateByPrimaryKey(ExtEproduct record);
}